#! /bin/sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &  # start x-hotkey daemon
nitrogen --restore
picom &
~/.config/polybar/launch.sh --$( cat ~/.config/polybar/theme )
xsetroot -cursor_name left_ptr
# ~/.config/bspwm/startup.sh &

# monitor configuration
source ~/.config/bspwm/monitors

# visual configuration
bspc config border_width 5
bspc config focused_border_color \#D7402E
bspc config active_border_color \#B2B2B2
bspc config window_gap 30
bspc config split_ratio 0.58

# alt-cursor click movement and resizing
bspc config pointer_modifier mod1
bspc config pointer_action3 resize_side
bspc config pointer_action3 resize_corner
bspc config pointer_action1 move

# application-specific rules
bspc rule -a Xfce4-settings-manager state=floating follow=on
bspc rule -a Thunar state=floating follow=on
bspc rule -a Spotify state=floating hidden=on
bspc rule -a Xscreensaver-demo state=floating
