#! /bin/sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &  # start x-hotkey daemon
nitrogen --restore
xsetroot -cursor_name left_ptr
picom --experimental-backends --backend glx --xrender-sync-fence &
~/.config/bspwm/subscriber &

# monitor configuration
source ~/.config/bspwm/monitors

# visual configuration
bspc config border_width 0
bspc config focused_border_color \#D7402E
bspc config active_border_color \#484848
bspc config window_gap 30
bspc config split_ratio 0.50
bspc config pointer_motion_interval 7

# alt-cursor click movement and resizing
bspc config pointer_modifier mod1
bspc config pointer_action3 resize_side
bspc config pointer_action3 resize_corner
bspc config pointer_action1 move
bspc config automatic_scheme longest_side
bspc config focus_follows_pointer true

# application-specific rules
bspc rule -a *:kitty state=pseudo_tiled rectangle=840x540+0+0
bspc rule -a openrgb state=floating follow=on center=true
bspc rule -a Xfce4-settings-manager state=floating follow=on center=true
bspc rule -a Thunar state=floating follow=on center=true
bspc rule -a Spotify state=floating hidden==on center=true
bspc rule -a spotify state=floating hidden==on center=true
bspc rule -a Xscreensaver-demo state=floating center=true
bspc rule -a Gpick state=floating center=true
bspc rule -a Nm-connection-editor state=floating center=true
bspc rule -a Xfce4-session-settings state=floating center=true
bspc rule -a Xfce4-power-manager-settings state=floating center=true
bspc rule -a Pavucontrol state=floating center=true
bspc rule -a Pamac-manager state=floating center=true
#bspc rule -a Eog state=floating center=true
bspc rule -a Xfce4-mime-settings state=floating center=true
bspc rule -a Gwyddion state=floating center=true
bspc rule -a 'Photoshop.exe' state=psuedo_tiled
bspc rule -a Pamac-manager state=floating center=true
bspc rule -a manjaro-settings-manager state=floating center=true
bspc rule -a matplotlib state=floating center=true
bspc rule -a feh state=floating center=true
bspc rule -a Nitrogen state=floating center=true
bspc rule -a Lightdm-gtk-greeter-settings state=floating center=true
bspc rule -a Blueman-manager state=floating center=true
bspc rule -a Zathura state=pseudo_tiled
bspc rule -a System-config-printer.py state=floating center=true
bspc rule -a System-config-printer.py state=floating center=true
bspc rule -a Nvidia-settings state=floating center=true
bspc rule -a jetbrains-studio state=pseudo_tiled center=true
bspc rule -a tabbed state=tiled center=true
bspc rule -a Peek state=floating center=true
bspc rule -a org.remmina.Remmina state=fullscreen
bspc rule -a weka-gui-GUIChooser state=floating
bspc rule -a Matplotlib state=floating
bspc rule -a 'VirtualBox Manager' state=floating
bspc rule -a 'Manjaro Settings Manager' state=floating
bspc rule -a 'VirtualBox Machine' state=fullscreen
bspc rule -a 'VirtualBoxVM' state=floating
bspc rule -a 'jetbrains-pycharm-ce' state=floating
bspc rule -a yad-calendar state=floating

# setup bar
sleep 3
~/.config/polybar/launch.sh --$( cat ~/.config/polybar/theme )
